name: Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up environment variable for Sentry Auth Token
      - name: Set up SENTRY_AUTH_TOKEN
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          echo "Sentry Auth Token is set"
          # Add other deployment steps here
